name: Continuous Integration.
on:
  pull_request:
    types:
      - opened
    branches:
      - dev
      - staging      

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Node LTS versions
      uses: msimerson/node-lts-versions@v1.1.1
    - run: npm install --force
    - name: Run test scripts
      run: npm test --ci --coverage
    # - name: Coverage
    #     run: npm run test:cov

  # coverage:
  #       runs-on: ubuntu-latest
  #       if: "!contains(github.event.head_commit.message, '[skip ci]')"
  #       steps:
  #           - uses: actions/checkout@v1
  #           - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
  #             with:
  #                 github-token: ${{ secrets.GITHUB_TOKEN }}
  #                 threshold: 95
    
